#!/bin/bash

#upgrade image uncomment only to upgrade image
#docker build -t gjcode/gjcode-pds:1.0.4 .
# build image uncomment only for the very first run 
#docker build -t pds-lab4 .
# run the container with volumes
docker run -it --rm -v $PWD:/home/lab4/ pds-lab4