FROM gjcode/gjcode-pds:1.0.4
LABEL author="GJCode"
#COPY . home
#COPY src/run-lab home/lab4
WORKDIR /home/lab4/src
#RUN apt-get install libboost-all-dev -y
#CMD ["valgrind", "--leak-check=full", "--show-leak-kinds=all", "./lab4"]